name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # https://github.com/marketplace/actions/build-and-push-docker-images
    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: macbre/nginx
        cache-from: |
          ghcr.io/macbre/nginx-http3:latest

    - name: Inspect images
      run: |
        docker images | head -n3

    - name: Run nginx -V
      run: |
        docker run -t macbre/nginx nginx -V | sed 's/\-\-/\n\t--/g' | tee

    - name: Serve a static asset
      run: |
        # expand commands
        set -x

        ./run-docker.sh &

        sleep 2; docker ps
        curl -v --compressed 0.0.0.0:8888 2>&1 | tee /tmp/out

        grep --fixed-strings '< Server: nginx' /tmp/out
        grep --fixed-strings '< Content-Encoding: br' /tmp/out
        grep --fixed-strings '<p>It works!</p>' /tmp/out


        curl -v --compressed --insecure https://0.0.0.0:8889 2>&1 | tee /tmp/h2

        grep --fixed-strings '< HTTP/2 200' /tmp/h2
        grep --fixed-strings '< server: nginx' /tmp/h2
        grep --fixed-strings '<p>It works!</p>' /tmp/h2


        docker run --rm --network host ymuski/curl-http3 \
          curl -v --insecure https://localhost:8889 --http3 2>&1 | tee /tmp/h3

        grep --fixed-strings '< HTTP/3 200' /tmp/h3
        grep --fixed-strings '< server: nginx' /tmp/h3
        grep --fixed-strings '< alt-svc: h3-27=":8889"; ma=86400, h3-28=":8889"; ma=86400, h3-29=":8889"; ma=86400' /tmp/h3
        grep --fixed-strings '< quic-status: quic' /tmp/h3
        grep --fixed-strings '<p>It works!</p>' /tmp/h3

        docker logs test_nginx
