name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --tag ${{ github.repository }}

    - name: Run nginx -V
      run: docker run -t ${{ github.repository }} nginx -V

    - name: Serve a static asset
      run: |
        docker run --rm -p 0.0.0.0:8888:80 -v "$PWD/tests":/static:ro  -v "$PWD/tests/static.conf":/etc/nginx/conf.d/static.conf:ro --name test_nginx -t ${{ github.repository }}
        sleep 2; docker ps
        curl -v --compressed 0.0.0.0:8888
        docker logs test_nginx
