name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: |
        docker build . \
          --tag ${{ github.repository }} \
          --cache-from macbre/nginx-brotli:latest
        docker images

    - name: Run nginx -V
      run: docker run -t ${{ github.repository }} nginx -V

    - name: Serve a static asset
      run: |
        docker run --detach --rm -p 0.0.0.0:8888:80 -v "$PWD/tests":/static:ro  -v "$PWD/tests/static.conf":/etc/nginx/conf.d/static.conf:ro -v "$PWD/tests/env.conf":/etc/nginx/main.d/env.conf:ro --env FOO=foo-test-value --name test_nginx -t ${{ github.repository }}
        sleep 2; docker ps
        curl -v --compressed 0.0.0.0:8888 2>&1 | tee /tmp/out

        # assert response headers presense
        grep 'X-Foo: foo-test-value' /tmp/out

        docker logs test_nginx
